-- Populate surahs table
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (1, 'الفاتحة', 'Al-Fatiha', 'Meccan', 7);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (2, 'البقرة', 'Al-Baqarah', 'Medinan', 286);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (3, 'آل عمران', 'Aal-E-Imran', 'Medinan', 200);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (4, 'النساء', 'An-Nisa', 'Medinan', 176);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (5, 'المائدة', 'Al-Maidah', 'Medinan', 120);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (6, 'الأنعام', 'Al-Anam', 'Meccan', 165);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (7, 'الأعراف', 'Al-Araf', 'Meccan', 206);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (8, 'الأنفال', 'Al-Anfal', 'Medinan', 75);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (9, 'التوبة', 'At-Tawbah', 'Medinan', 129);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (10, 'يونس', 'Yunus', 'Meccan', 109);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (11, 'هود', 'Hud', 'Meccan', 123);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (12, 'يوسف', 'Yusuf', 'Meccan', 111);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (13, 'الرعد', 'Ar-Rad', 'Medinan', 43);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (14, 'إبراهيم', 'Ibrahim', 'Meccan', 52);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (15, 'الحجر', 'Al-Hijr', 'Meccan', 99);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (16, 'النحل', 'An-Nahl', 'Meccan', 128);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (17, 'الإسراء', 'Al-Isra', 'Meccan', 111);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (18, 'الكهف', 'Al-Kahf', 'Meccan', 110);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (19, 'مريم', 'Maryam', 'Meccan', 98);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (20, 'طه', 'Taha', 'Meccan', 135);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (21, 'الأنبياء', 'Al-Anbiya', 'Meccan', 112);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (22, 'الحج', 'Al-Hajj', 'Medinan', 78);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (23, 'المؤمنون', 'Al-Muminun', 'Meccan', 118);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (24, 'النور', 'An-Nur', 'Medinan', 64);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (25, 'الفرقان', 'Al-Furqan', 'Meccan', 77);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (26, 'الشعراء', 'Ash-Shuara', 'Meccan', 227);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (27, 'النمل', 'An-Naml', 'Meccan', 93);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (28, 'القصص', 'Al-Qasas', 'Meccan', 88);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (29, 'العنكبوت', 'Al-Ankabut', 'Meccan', 69);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (30, 'الروم', 'Ar-Rum', 'Meccan', 60);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (31, 'لقمان', 'Luqman', 'Meccan', 34);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (32, 'السجدة', 'As-Sajdah', 'Meccan', 30);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (33, 'الأحزاب', 'Al-Ahzab', 'Medinan', 73);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (34, 'سبأ', 'Saba', 'Meccan', 54);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (35, 'فاطر', 'Fatir', 'Meccan', 45);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (36, 'يس', 'Ya-Sin', 'Meccan', 83);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (37, 'الصافات', 'As-Saffat', 'Meccan', 182);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (38, 'ص', 'Sad', 'Meccan', 88);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (39, 'الزمر', 'Az-Zumar', 'Meccan', 75);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (40, 'غافر', 'Ghafir', 'Meccan', 85);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (41, 'فصلت', 'Fussilat', 'Meccan', 54);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (42, 'الشورى', 'Ash-Shura', 'Meccan', 53);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (43, 'الزخرف', 'Az-Zukhruf', 'Meccan', 89);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (44, 'الدخان', 'Ad-Dukhan', 'Meccan', 59);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (45, 'الجاثية', 'Al-Jathiyah', 'Meccan', 37);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (46, 'الأحقاف', 'Al-Ahqaf', 'Meccan', 35);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (47, 'محمد', 'Muhammad', 'Medinan', 38);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (48, 'الفتح', 'Al-Fath', 'Medinan', 29);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (49, 'الحجرات', 'Al-Hujurat', 'Medinan', 18);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (50, 'ق', 'Qaf', 'Meccan', 45);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (51, 'الذاريات', 'Adh-Dhariyat', 'Meccan', 60);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (52, 'الطور', 'At-Tur', 'Meccan', 49);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (53, 'النجم', 'An-Najm', 'Meccan', 62);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (54, 'القمر', 'Al-Qamar', 'Meccan', 55);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (55, 'الرحمن', 'Ar-Rahman', 'Medinan', 78);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (56, 'الواقعة', 'Al-Waqiah', 'Meccan', 96);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (57, 'الحديد', 'Al-Hadid', 'Medinan', 29);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (58, 'المجادلة', 'Al-Mujadila', 'Medinan', 22);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (59, 'الحشر', 'Al-Hashr', 'Medinan', 24);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (60, 'الممتحنة', 'Al-Mumtahanah', 'Medinan', 13);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (61, 'الصف', 'As-Saff', 'Medinan', 14);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (62, 'الجمعة', 'Al-Jumuah', 'Medinan', 11);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (63, 'المنافقون', 'Al-Munafiqun', 'Medinan', 11);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (64, 'التغابن', 'At-Taghabun', 'Medinan', 18);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (65, 'الطلاق', 'At-Talaq', 'Medinan', 12);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (66, 'التحريم', 'At-Tahrim', 'Medinan', 12);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (67, 'الملك', 'Al-Mulk', 'Meccan', 30);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (68, 'القلم', 'Al-Qalam', 'Meccan', 52);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (69, 'الحاقة', 'Al-Haqqah', 'Meccan', 52);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (70, 'المعارج', 'Al-Maarij', 'Meccan', 44);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (71, 'نوح', 'Nuh', 'Meccan', 28);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (72, 'الجن', 'Al-Jinn', 'Meccan', 28);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (73, 'المزمل', 'Al-Muzzammil', 'Meccan', 20);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (74, 'المدثر', 'Al-Muddaththir', 'Meccan', 56);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (75, 'القيامة', 'Al-Qiyamah', 'Meccan', 40);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (76, 'الإنسان', 'Al-Insan', 'Medinan', 31);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (77, 'المرسلات', 'Al-Mursalat', 'Meccan', 50);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (78, 'النبأ', 'An-Naba', 'Meccan', 40);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (79, 'النازعات', 'An-Naziat', 'Meccan', 46);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (80, 'عبس', 'Abasa', 'Meccan', 42);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (81, 'التكوير', 'At-Takwir', 'Meccan', 29);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (82, 'الإنفطار', 'Al-Infitar', 'Meccan', 19);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (83, 'المطففين', 'Al-Mutaffifin', 'Meccan', 36);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (84, 'الإنشقاق', 'Al-Inshiqaq', 'Meccan', 25);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (85, 'البروج', 'Al-Buruj', 'Meccan', 22);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (86, 'الطارق', 'At-Tariq', 'Meccan', 17);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (87, 'الأعلى', 'Al-Ala', 'Meccan', 19);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (88, 'الغاشية', 'Al-Ghashiyah', 'Meccan', 26);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (89, 'الفجر', 'Al-Fajr', 'Meccan', 30);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (90, 'البلد', 'Al-Balad', 'Meccan', 20);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (91, 'الشمس', 'Ash-Shams', 'Meccan', 15);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (92, 'الليل', 'Al-Layl', 'Meccan', 21);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (93, 'الضحى', 'Ad-Duha', 'Meccan', 11);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (94, 'الشرح', 'Ash-Sharh', 'Meccan', 8);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (95, 'التين', 'At-Tin', 'Meccan', 8);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (96, 'العلق', 'Al-Alaq', 'Meccan', 19);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (97, 'القدر', 'Al-Qadr', 'Meccan', 5);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (98, 'البينة', 'Al-Bayyinah', 'Medinan', 8);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (99, 'الزلزلة', 'Az-Zalzalah', 'Medinan', 8);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (100, 'العاديات', 'Al-Adiyat', 'Meccan', 11);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (101, 'القارعة', 'Al-Qariah', 'Meccan', 11);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (102, 'التكاثر', 'At-Takathur', 'Meccan', 8);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (103, 'العصر', 'Al-Asr', 'Meccan', 3);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (104, 'الهمزة', 'Al-Humazah', 'Meccan', 9);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (105, 'الفيل', 'Al-Fil', 'Meccan', 5);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (106, 'قريش', 'Quraysh', 'Meccan', 4);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (107, 'الماعون', 'Al-Maun', 'Meccan', 7);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (108, 'الكوثر', 'Al-Kawthar', 'Meccan', 3);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (109, 'الكافرون', 'Al-Kafirun', 'Meccan', 6);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (110, 'النصر', 'An-Nasr', 'Medinan', 3);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (111, 'المسد', 'Al-Masad', 'Meccan', 5);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (112, 'الإخلاص', 'Al-Ikhlas', 'Meccan', 4);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (113, 'الفلق', 'Al-Falaq', 'Meccan', 5);
INSERT OR IGNORE INTO surahs (id, name_ar, name_en, revelation_type, verse_count) VALUES (114, 'الناس', 'An-Nas', 'Meccan', 6);

-- Populate hizbs table
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (1, 1);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (2, 2);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (3, 3);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (4, 4);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (5, 5);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (6, 6);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (7, 7);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (8, 8);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (9, 9);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (10, 10);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (11, 11);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (12, 12);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (13, 13);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (14, 14);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (15, 15);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (16, 16);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (17, 17);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (18, 18);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (19, 19);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (20, 20);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (21, 21);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (22, 22);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (23, 23);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (24, 24);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (25, 25);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (26, 26);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (27, 27);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (28, 28);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (29, 29);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (30, 30);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (31, 31);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (32, 32);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (33, 33);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (34, 34);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (35, 35);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (36, 36);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (37, 37);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (38, 38);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (39, 39);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (40, 40);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (41, 41);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (42, 42);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (43, 43);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (44, 44);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (45, 45);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (46, 46);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (47, 47);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (48, 48);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (49, 49);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (50, 50);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (51, 51);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (52, 52);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (53, 53);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (54, 54);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (55, 55);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (56, 56);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (57, 57);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (58, 58);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (59, 59);
INSERT OR IGNORE INTO hizbs (id, hizb_number) VALUES (60, 60);
